### ISSUE TITLE
Checklist da R1

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2018.1-Reabilitacao-Motora#111]
### Descrição:
Mostra os passos a fazer para a preparação do projeto para a R1

### Critérios de Aceitação
- [ ] Todos as tarefas completas

### Tarefas

**Todos**
- [x] Apresentação R1
- [x] Completar planilha de horas
- [x] Aprovar PR

**EPS** 

- [x] Atualizar canvas
- [x] Passar atas de reuniao e dojo para markdown
- [x] Atualizar arquitetura
- [x] Rodar doxygen novamente 
- [x] Alinhamento de todas as branchs devel e master
- [x] Revisar documentos do Git
- [x] Revisar EAP
- [x] Passar a EAP pra markdown e subir no gh-pages
- [x] Revisar EVM
- [x] Passar EVM pro gh-pages
- [x] Revisar Backlog
- [x] Revisar Roadmap
- [ ] matriz de rastreabilidade
- [x] Fechar o feedback 1 feito pela carla
- [x] Fechar o feedback 2 feito pela carla
- [x] Terminar de completar a pagina home do repo, tem campo default

**MDS**
- [x] Revisar doc de arquitetura/VISÃO
- [x] Enviar pr de rotular movimentos
- [x] Reabrir issue de refatoração do protótipo de alta fidelidade
- [x] Atualizar prototipo

**Comment by RomeuCarvalhoAntunes** [comment]
Revisei o Roadmap, colocando algumas tarefas que não existiam, revisei o backlog e atualizei os links

**Comment by RomeuCarvalhoAntunes** [comment]
Estruturei a agenda da R1 no canal de comunicação oficial do projeto Slack
1 - Apresentação do grupo e do projeto (Romeu)
2 - Visão de produto do projeto (Lucas)
3 - Aonde estamos no roadmap, riscos e tratamentos (Romeu e Moura)
4 - Arquitetura (Falcão)
5 - DevOps (Moura)

6 - MDS Apresentar o que tem feito (Definir quem e o que iremos apresentar) 
 	- Viabilidade tecnica do projeto 
	- O que fizemos 
	- Aonde iremos Chegar

**Comment by RomeuCarvalhoAntunes** [comment]
EVM na wiki !

**Comment by RomeuCarvalhoAntunes** [comment]
Feedback 1 Fechado !
