### ISSUE TITLE
Ter acesso ao código da implementação atual da solução

### ISSUE THREAD

**Issue by victorcmoura** [fga-gpp-mds/2018.1-Reabilitacao-Motora#12]
Ter acesso ao código da implementação atual da solução
---
### Descrição:
Ter acesso ao código fonte da solução de software implementada atualmente.

### Critérios de aceitação
Para considerarmos a situação de acesso ao código fonte, devemos:
- [ ] Ter acesso a um fork ou ao repositório original do projeto
- [ ] Ter a capacidade de editar o código sem impactar no repositório original
- [ ] Ter autorização para utilizarmos o código em nosso projeto

### Tasks
Seção para issues mais complexas. Todas as tarefas que devem estar funcionando no fim da issue:
- [X] Solicitar a @RochaCarla para que tenhamos acesso ao código
