### ISSUE TITLE
Definir Roadmap

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2018.1-Reabilitacao-Motora#20]
### Descrição:
Tomando como base o Product Backlog descrever um roadmap contendo o fluxo de atividades dentro de cada sprint.

### Critérios de Aceitação
- [ ] Documento devidamente versionado.
- [ ] Todos os itens do Product Backlog dentro do roadmap

### Tarefas
- [ ] Filtrar dificuldade das estórias de usuário
- [ ] Classificar estórias de usuário
- [ ] Dividir as estórias de usuário dentro de cada sprint

**Comment by arthurbdiniz** [comment]
Atualizando documentação
