### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-gpp-mds/2018.1-Reabilitacao-Motora#63]
### Descrição:
Documento para mostrar a timeline e andamento do projeto até a release 1.

### Critérios de Aceitação
- [ ] Descrição de todas as sprints até a release 1.

### Tarefas
- [x] Equilibrar roadmap a fins de evitar sobrecarga de MDS.
- [x] Entregar MVP até a release 1.
